'use strict';
var through2 = require('through2'),
    Xtemplate = require('kissy-xtemplate'),
    gutil = require('gulp-util'),
    PluginError = gutil.PluginError,
    path = require('path'),
    minimatch = require("minimatch"),
    gulp = require("gulp"),
	kmd = require("kmd");

var pathSeparatorRe = /[\/\\]/g;

var depMap = {},
    realDepMap = {};


function endsWith(str, suffix) {
    var ind = str.length - suffix.length;
    return ind >= 0 && str.indexOf(suffix, ind) === ind;
}

function parseExt(ext) {
    var _ext = {};

    if(!ext) {
        _ext = kmd.config("ext") || {
            min:"-min.js",
            src:".js"
        };
    }else if(typeof ext == "string") {
        _ext = {
            min:ext,
            src:".js"
        }
    }else {
        _ext = {
            min:ext.min||"-min.js",
            src:ext.src||".js"
        }
    }
    return _ext;
}


module.exports ={
    config: kmd.config,
    xtpl: function (options) {

            options = options || {};
            options.outputCharset = options.outputCharset || 'utf8';
            options.inputCharset = options.inputCharset || 'utf8';

            var xtemp = new Xtemplate(options);

        	return through2.obj(function (file, enc, callback ) {
        		if (file.isNull()) {
        			this.push(file);
        			return cb();
        		}

        		if (file.isStream()) {
        			this.emit('error', new gutil.PluginError('gulp-kmc', 'Streaming not supported'));
        			return cb();
        		}

        		try {
                    if(file && file.path){
                        file.path = file.path.replace('.xtpl.html', '-xtpl.js');
                    }
                    var code = xtemp._compile(file.contents.toString(), file.path, options.inputCharset, options.outputCharset);
                    code = kmd.kissy2cmd.parse(code.toString(),{fromString:true});
        			file.contents = new Buffer(code);
        		} catch (err) {
        			this.emit('error', new gutil.PluginError('gulp-kmc', err));
        		}

        		this.push(file);
        		return callback();
        	});
        },
    convert: function(opt) {
        var buffer = [],
            opt = opt||{},
            ext = parseExt(opt.ext);

        opt = opt || {};

	    function k2cmd(file, enc, callback) {
            if (file.isNull()) {
                return callback();
            }

            if (file.isStream()) {
                this.emit('error', new PluginError('gulp-kmc',  'Streaming not supported'));
                return callback();
            }

            var ignore = false;

            if(opt.exclude) {
                ignore = opt.exclude.some(function(item) {
                    return path.dirname(file.path).split(pathSeparatorRe).some(function(pathName) {
                        return minimatch(pathName, item);
                    });
                });
            }

            if(!ignore && opt.ignoreFiles) {
                ignore = opt.ignoreFiles.some(function(item) {
                    return minimatch(path.basename(file.path), item);
                });
            }

            if(ignore) {
                this.push(file);
                return callback();
            }

            file.realPath = file.path;
            var r = kmd.convert(file.contents.toString(), {
                                            filePath:file.path,
                                            fixModuleName:opt.fixModuleName || kmd.config("fixModuleName")
                                        });


            if(r.dependencies.length && !depMap[r.moduleInfo.moduleName]) {
                var requires = [],realRequires = [];
                r.dependencies.forEach(function(dep) {
                    requires.push(dep);
                    realRequires.push(dep);
                });
                realDepMap[r.moduleInfo.moduleName] = { requires: realRequires };
                depMap[r.moduleInfo.moduleName] = { requires: requires };
            }

            if(opt.minify) {
                var new_path = file.path.replace(/\.js$/, ext.min),
                    new_file = new gutil.File({
                                   contents:new Buffer(r.minify),
                                   path:new_path,
                                   base:file.base
                               });
                new_file.moduleInfo = r.moduleInfo;
                buffer.push(new_file);

            }

            file.path = file.path.replace(/\.js$/,ext.src);
            file.contents = new Buffer(r.source);
            file.moduleInfo = r.moduleInfo;
            buffer.push(file);
            callback(null);
        }

        function endStream(callback) {
            kmd.config("modules",realDepMap);

            if(kmd.config("depFilePath")) {
                var depFilePath = kmd.config("depFilePath");

                var code ="/*generated by KMD*/\nKISSY.config('modules'," + JSON.stringify(depMap,null,4) +');'


                this.push(new gutil.File({
                     contents:new Buffer(code),
                     path:depFilePath.replace(/\.js$/,ext.src),
                     base:path.dirname(depFilePath)
                }));

                this.push(new gutil.File({
                     contents:new Buffer(kmd.minify(code)),
                     path:depFilePath.replace(/\.js$/,ext.min),
                     base:path.dirname(depFilePath)
                }));
            }
            var self = this;

            buffer.forEach(function(file){
               self.push(file);
            });
            return callback();
        }

	    return through2.obj(k2cmd, endStream);
    },
    combo: function(opt) {

       var combined = {},
           opt = opt || {},
           ext = parseExt(opt.ext),
           config = null;

       var buffer = [];

       opt = opt || {};

       function combo(_file, callback) {
            var combinedFile = [];

            if(combined[_file.path]) {
                return combinedFile;
            }

            if(opt && opt.files && opt.files.length) {
                opt.files.forEach(function(file){
                    if(path.resolve(file.src) == _file.path){
                       var info = kmd.combo(_file.path),
                           src = file.dest.replace(/\.js$/,ext.src),
                           dest = file.dest.replace(/\.js$/,ext.min);

                       var extra = "/*\n"+ new Date() +"\ncombined files by KMD:\n\n" + info.files.join("\n")+"\n*/\n\n";

                       var srcFile = new gutil.File({
                                        base:path.dirname(file.dest),
                                        path:src,
                                        contents: new Buffer(extra+info.source.join("\n"))
                                    });

                       srcFile.moduleInfo = _file.moduleInfo;
                       buffer.push(srcFile);

                       if(opt.minify) {
                            var minifyFile = new gutil.File({
                                                base:path.dirname(file.dest),
                                                path:dest,
                                                contents: new Buffer(info.minify.join(""))
                                             });
                            minifyFile.moduleInfo = _file.moduleInfo;
                            buffer.push(minifyFile);
                       }

                       gutil.log('combined  file ' + gutil.colors.green(file.dest) + ' is created.');

                    }
                });
            }
       }

       function endStream(callback) {
           if (buffer.length === 0) return this.emit('end');
           var self = this;

           buffer.reverse().forEach(function(file){
               self.push(file);
           });

           return callback();
       }

       return through2.obj(function (file, enc, callback) {
            if (file.isNull()) {
                return callback();
            }

            if (file.isStream()) {
                this.emit('error', new PluginError('gulp-kmc',  'Streaming not supported'));
                return callback();
            }

            combo(file);

            buffer.push(file);
            return callback();
        },endStream);
    },
    dest: function(outFolder, opt){

        return through2.obj(function(file, enc, callback){
            var folder = null,
                base = path.basename(file.base);

            if(file.moduleInfo) {
                var pkg = file.moduleInfo.package;
                if(outFolder[pkg.name]) {
                    folder = outFolder[pkg.name];
                }else if(outFolder["*"]) {
                    folder = outFolder[pkg.name];
                }else {
                    folder = outFolder;
                }
            }else {
                folder = outFolder["*"] || outFolder;
            }
            if(!folder) {
                gutil.log(gutil.colors.green('[error]')+' file '+gutil.colors.red(file.path)+' does not have a valid out put folder! ');
                return callback();
            }
            gulp.dest.call(gulp, folder, opt).write(file);
            return callback();
        });
    }
}
